# Generated by Django 3.2.14 on 2022-07-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='surface_img',
            field=models.ImageField(blank=True, null=True, upload_to='surface_img/', verbose_name='文章封面图'),
        ),
    ]
