# Generated by Django 3.2.14 on 2023-01-20 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20220725_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='surface_img',
        ),
    ]
