# Generated by Django 3.2.14 on 2023-05-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_articles_surface_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagid', models.IntegerField(default=1)),
                ('tagcontext', models.CharField(default='tagcontext', max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='articles',
            name='tagid',
            field=models.IntegerField(default=1),
        ),
    ]
