# Generated by Django 3.2.14 on 2023-05-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20230506_2018'),
    ]

    operations = [        

    ]
