# Generated by Django 3.2.14 on 2023-05-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20230513_1411'),
    ]

    operations = [
       

    ]
