# Generated by Django 3.2.14 on 2023-05-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20230513_1415'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='Articles',
        # ),
        # migrations.RemoveField(
        #     model_name='tags',
        #     name='id',
        # ),
        # migrations.AlterField(
        #     model_name='tags',
        #     name='tagid',
        #     field=models.AutoField(primary_key=True, serialize=False),
        # ),
    ]
