# Generated by Django 3.2.14 on 2023-05-15 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20230513_1535'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='Articles',
        # ),
        # migrations.RemoveField(
        #     model_name='tags',
        #     name='id',
        # ),
        migrations.AddField(
            model_name='passages',
            name='is_proj',
            field=models.BooleanField(default=False),
        ),
        # migrations.AlterField(
        #     model_name='tags',
        #     name='tagid',
        #     field=models.AutoField(primary_key=True, serialize=False),
        # ),
    ]
